### ISSUE TITLE
No deployment testing

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/documentation-builder#130]
_From @evilnick on May 30, 2018 12:11_

We ran into this issue on Juju docs.

Documentation-builder created the pages okay.
The run script works 
The jenkins job to deploy to staging works
The jenkins job to deploy works

However, one of the pages generated a jinja2 error, 
 ```
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'db' is undefined
...
```
https://paste.ubuntu.com/p/jgS9SkHvgH/

Which on the live site returns a 500

Leaving aside the specific problem that caused this error, it seems like there ought to be some sort of minimal testing either in the run script, documentation-builder or the jenkins job that actually checks the pages have been generated and work.

_Copied from original issue: canonical-webteam/generator-canonical-webteam#71_

**Comment by nottrobin** [comment]
_From @pmatulis on June 26, 2018 17:32_

Another instance of this has been identified. This time the file can be built and viewed locally but not remotely.
See: https://github.com/canonical-webteam/documentation-builder/issues/122

**Comment by nottrobin** [comment]
_From @pmatulis on July 4, 2018 20:8_

Another instance of this has been identified. This time I have no idea which page is affected. The build to staging fails so this is a significant blocker:

```Traceback (most recent call last):
  File "/usr/local/bin/documentation-builder", line 17, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/cli.py", line 164, in main
    Builder(**arguments)
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/builder.py", line 120, in __init__
    version_branches
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/builder.py", line 241, in build_branch
    metadata
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/operations.py", line 152, in parse_markdown
    metadata['content'] = parser.convert(file_parts.content)
  File "/usr/local/lib/python3.5/dist-packages/markdown/__init__.py", line 371, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/local/lib/python3.5/dist-packages/markdown/blockparser.py", line 65, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/local/lib/python3.5/dist-packages/markdown/blockparser.py", line 80, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/local/lib/python3.5/dist-packages/markdown/blockparser.py", line 98, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/extensions.py", line 134, in run
    parent.append(etree.fromstring(markup))
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 414
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Luckily, the only change this build should bring in is noted in a single PR:

```Commit message: "Merge pull request #2806 from pmatulis/2772_clarifying-maas-pages"```

The only thing that I can detect that is out of the ordinary is that I added a TODO note without adding the 'TODO' keyword (the fix for this is in a subsequent [PR](https://github.com/juju/docs/pull/2832/files); see clouds-manual.md).

**Comment by nottrobin** [comment]
_From @pmatulis on July 5, 2018 13:58_

This last was caused by [corrections to admonishments](https://github.com/juju/docs/pull/2766) in the 1.25 series. After [reverting](https://github.com/juju/docs/pull/2842) the builder worked once again.

**Comment by tbille** [comment]
We deliver html templates via nginx now. Not relevant anymore.
