### ISSUE TITLE
The snap (rev 35) crashes when creating versioned documentation

### ISSUE THREAD

**Issue by caldav** [canonical-webteam/documentation-builder#89]
Version 1.5.0 installed from pip works fine, but revision 35 of the snap (1.5.0) crashes when fetching version branches of a doc repo.

Trace when used in the `run` script of https://github.com/canonical-websites/docs.ubuntu.com

```
david@helena:~/documentation/docs.ubuntu.com$ ./run
yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "0.27.5" while you're on "0.24.4".
Done in 20.08s.
yarn run v0.24.4
$ node-sass --include-path node_modules static/sass --output static/css 
Rendering Complete, saving .css file...
Wrote CSS to /home/david/documentation/docs.ubuntu.com/static/css/global.css
Rendering Complete, saving .css file...
Wrote CSS to /home/david/documentation/docs.ubuntu.com/static/css/homepage.css
Wrote 2 CSS files to /home/david/documentation/docs.ubuntu.com/static/css
Done in 0.70s.
Cloning into 'docs/conjure-up'...
remote: Counting objects: 249, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 249 (delta 28), reused 73 (delta 14), pack-reused 161
Receiving objects: 100% (249/249), 1.31 MiB | 422.00 KiB/s, done.
Resolving deltas: 100% (112/112), done.
Traceback (most recent call last):
  File "/snap/documentation-builder/35/documentation-builder", line 17, in <module>
    cli.main(sys.argv[1:])
  File "/snap/documentation-builder/35/ubuntudesign/documentation_builder/cli.py", line 164, in main
    Builder(**arguments)
  File "/snap/documentation-builder/35/ubuntudesign/documentation_builder/builder.py", line 115, in __init__
    output_path
  File "/snap/documentation-builder/35/ubuntudesign/documentation_builder/operations.py", line 223, in prepare_version_branches
    Repo.clone_from(base_directory, branch_base_directory, branch=name)
  File "/snap/documentation-builder/35/lib/python3.5/site-packages/git/repo/base.py", line 966, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/snap/documentation-builder/35/lib/python3.5/site-packages/git/repo/base.py", line 912, in _clone
    finalize_process(proc, stderr=stderr)
  File "/snap/documentation-builder/35/lib/python3.5/site-packages/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/snap/documentation-builder/35/lib/python3.5/site-packages/git/cmd.py", line 335, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --branch=2.1.2 -v docs/conjure-up /home/david/snap/documentation-builder/35/.cache/documentation-builder/tmp8sjzfwox' returned with exit code -31
stderr: 'Cloning into '/home/david/snap/documentation-builder/35/.cache/documentation-builder/tmp8sjzfwox'...
warning: templates not found /share/git-core/templates
done.
fatal: The remote end hung up unexpectedly
'
```

**Comment by nottrobin** [comment]
Confirmed. This is also an issue for the stable version, `1.4.3`.

**Comment by frankiegranato** [comment]
@nottrobin as this is "critical", would you be able to do it next iteration (iteration 10)?

**Comment by nottrobin** [comment]
@frankiegranato yep, I'd say that would be a good idea

**Comment by frankiegranato** [comment]
@WillMoggridge I'm removing this from the Iteration 11 epic. Handing over to Vanilla & Base.

**Comment by nottrobin** [comment]
@frankiegranato @WillMoggridge I believe this is being taken care of by @anthonydillon - he's going to publish v1.5.1 following https://github.com/canonical-webteam/documentation-builder/pull/97 in Pip and snap, which should fix this.

@anthonydillon please update here with your progress on that.

**Comment by anthonydillon** [comment]
@caldav revision 36 of the snap (1.5.1) has been released. Could you please test the latest version.

**Comment by caldav** [comment]
r36 from latest/stable doesn't have the issue. LGTM

One thing: you might want to drop r35 from the latest/candidate channel.

**Comment by nottrobin** [comment]
@caldav is there any way to install r35? My understanding was you can only install the latest revision from any channel.

In any case, I'm not 100% convinced that r35 was broken - I think @anthonydillon installed it successfully. It may have been a transient bug in snap itself?

Can you see if you can install r35 and if so if it still breaks for you?

**Comment by caldav** [comment]
@nottrobin snap install documentation-builder --candidate (or --channel=candidate / --channel=latest/candidate) will install r35.

And yes, I've just tried r35 again and it passed as well.

**Comment by anthonydillon** [comment]
Sure, rev 36 is now both stable and candidate.
